### ISSUE TITLE
Cannot find corresponding file

### ISSUE THREAD

**Issue by ytrsh** [zhuolikevin/Simple-online-chatting#1]
```
Cannot find corresponding file
Traceback (most recent call last):
  File "d:\Python\Simple-online-chatting-master\Server.py", line 750, in <module>
    (USER_TOTAL,user_password, MESSAGE_LIST, USER_ADDR, LOGIN_LIST, LOGIN_TIME) = pre_setting()
  File "d:\Python\Simple-online-chatting-master\Server.py", line 225, in pre_setting
    allusers = userlist.readlines()                       # Read file in lines
UnboundLocalError: local variable 'userlist' referenced before assignment
```
I got this error while debugging server.py Check it out 👍

**Comment by zhuolikevin** [comment]
Did you have user_pass.txt at the same directory?

**Comment by ytrsh** [comment]
I ran it on file explorer. It is done now. Thanks
